Use echo groups on the header check

diff --git a/.github/workflows/kernel-checks.yml b/.github/workflows/kernel-checks.yml
--- a/.github/workflows/kernel-checks.yml
+++ b/.github/workflows/kernel-checks.yml
@@ -35,10 +35,35 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
 
       # Run checks
-      - name: Check File Headers
+      - env:
+          bashPass: \033[32;1mPASSED -
+          bashInfo: \033[33;1mINFO -
+          bashFail: \033[31;1mFAILED -
+          bashEnd:  \033[0m
+          stepName: Check File Headers
+        name: ${{ env.stepName }}
+        shell: bash
         run: |
+          # ${{ env.stepName }}
+          echo -e "::group::${{ env.bashInfo }} Install Dependencies ${{ env.bashEnd }}"
+
+          # Copy the common tools from the FreeRTOS/FreeRTOS repo.
           mv tools/.github/scripts/common inspect/.github/scripts
+
+          # Install the necessary python dependencies
           pip install -r inspect/.github/scripts/common/requirements.txt
           cd inspect
+
+          echo -e "::group::${{ env.bashInfo }} ${{ env.stepName }} ${{ env.bashEnd }}"
+
+          # Use the python script to check the copyright header of modified files.
           .github/scripts/kernel_checker.py --json ${HOME}/files_modified.json ${HOME}/files_added.json ${HOME}/files_renamed.json
-          exit $?
+          exitStatus=$?
+          echo -e "::endgroup::"
+
+          if [ $exitStatus -eq 0 ]; then
+            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+          else
+            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+          fi
+          exit $exitStatus
